import { NextRequest, NextResponse } from 'next/server';
import jwt from 'jsonwebtoken';
import dbConnect from '@/lib/dbConnect';
import { User } from '@/models/User';

// CORS headers for cross-origin requests from TrustInn
const corsHeaders = {
  'Access-Control-Allow-Origin': process.env.NEXT_PUBLIC_TRUSTINN_URL || 'https://trustinn.nitminer.com',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Access-Control-Max-Age': '86400',
};

/**
 * POST /api/auth/validate-nitminer-token
 * 
 * Validates JWT tokens generated by /api/auth/generate-token
 * Called by TrustInn to verify token authenticity and get user information
 * 
 * Request body:
 * {
 *   "token": "eyJhbGc..."
 * }
 * 
 * Response on success:
 * {
 *   "isValid": true,
 *   "user": {
 *     "id": "user_id",
 *     "email": "user@example.com",
 *     "name": "User Name",
 *     "role": "user",
 *     "isPremium": false,
 *     "trialCount": 3
 *   },
 *   "expiresAt": "2026-02-12T10:30:00Z"
 * }
 */
export async function POST(request: NextRequest) {
  try {
    // Parse request body
    const body = await request.json().catch(() => ({}));
    const token = body.token || request.headers.get('authorization')?.replace('Bearer ', '');

    if (!token || typeof token !== 'string') {
      console.log('[VALIDATE-NITMINER-TOKEN] No token provided');
      return NextResponse.json(
        { isValid: false, error: 'No token provided' },
        { status: 400, headers: corsHeaders }
      );
    }

    // Verify JWT token
    let decoded: any;
    try {
      decoded = jwt.verify(token, process.env.JWT_SECRET || 'your-secret-key', {
        issuer: 'nitminer-trustinn',
        audience: 'trustinn-app',
      });
    } catch (err: any) {
      console.log('[VALIDATE-NITMINER-TOKEN] Token verification failed:', err.message);
      return NextResponse.json(
        { isValid: false, error: 'Invalid or expired token' },
        { status: 401, headers: corsHeaders }
      );
    }

    if (!decoded.id || !decoded.email) {
      console.log('[VALIDATE-NITMINER-TOKEN] Invalid token payload');
      return NextResponse.json(
        { isValid: false, error: 'Invalid token payload' },
        { status: 401, headers: corsHeaders }
      );
    }

    // Verify user still exists and tokenVersion hasn't changed (logout invalidation)
    await dbConnect();
    const user = await User.findById(decoded.id);

    if (!user) {
      console.log('[VALIDATE-NITMINER-TOKEN] User not found:', decoded.id);
      return NextResponse.json(
        { isValid: false, error: 'User not found' },
        { status: 401, headers: corsHeaders }
      );
    }

    // Check if token has been invalidated (tokenVersion mismatch)
    if (decoded.tokenVersion !== user.tokenVersion) {
      console.log('[VALIDATE-NITMINER-TOKEN] Token invalidated (version mismatch)');
      return NextResponse.json(
        { isValid: false, error: 'Token has been invalidated' },
        { status: 401, headers: corsHeaders }
      );
    }

    // Calculate expiration time from JWT
    const expiresAt = new Date(decoded.exp * 1000).toISOString();

    console.log('[VALIDATE-NITMINER-TOKEN] Token validated successfully for:', decoded.email);

    return NextResponse.json(
      {
        isValid: true,
        token: token, // Return the validated token
        user: {
          id: user._id.toString(),
          mongoId: user._id.toString(),
          email: user.email,
          name: `${user.firstName} ${user.lastName}`.trim(),
          role: user.role || 'user',
          isPremium: user.isPremium,
          trialCount: user.trialCount,
          isEmailVerified: user.isEmailVerified,
          subscription: {
            plan: user.subscription?.plan || null,
            status: user.subscription?.status || null,
            startDate: user.subscription?.startDate?.toISOString() || null,
            endDate: user.subscription?.endDate?.toISOString() || null,
          },
        },
        expiresAt,
        issuedAt: decoded.issuedAt,
      },
      { status: 200, headers: corsHeaders }
    );
  } catch (error) {
    console.error('[VALIDATE-NITMINER-TOKEN] Error:', error);
    return NextResponse.json(
      { isValid: false, error: 'Internal server error' },
      { status: 500, headers: corsHeaders }
    );
  }
}

/**
 * GET /api/auth/validate-nitminer-token
 * 
 * Health check for validation endpoint
 */
export async function GET(request: NextRequest) {
  return NextResponse.json(
    {
      status: 'active',
      message: 'Token validation endpoint is operational',
      documentation: '/api/docs/auth/validate-nitminer-token',
      usage: 'POST with { "token": "..." } in body or Authorization header',
    },
    { status: 200, headers: corsHeaders }
  );
}

/**
 * OPTIONS /api/auth/validate-nitminer-token
 * 
 * CORS preflight support
 */
export async function OPTIONS(request: NextRequest) {
  return NextResponse.json({}, { status: 200, headers: corsHeaders });
}
